Repository RustAudio/rust-lv2, pull requests merged in 2020-03, with the labels that each got.

#50 Making features available for all methods
  atom/tests/atom_integration.rs
  core/derive/src/feature_collection_derive.rs
  core/src/extension.rs
  core/src/feature/cache.rs
  core/src/feature/core_features.rs
  core/src/feature/descriptor.rs
  core/src/feature/mod.rs
  core/src/plugin/mod.rs
  core/src/prelude.rs
  core/tests/amp.rs
  state/src/interface.rs
  state/src/lib.rs
  state/tests/integration.rs
  urid/src/feature.rs
Labels: enhancement

#53 Restoring the Windows support
  .travis.yml
  state/src/interface.rs
  state/src/lib.rs
  state/src/raw.rs
  state/src/storage.rs
  state/tests/integration.rs
  sys/build.rs
  sys/src/lib.rs
Labels: bug, enhancement

#57 Adding a `uri` attribute
  README.md
  atom/src/object.rs
  atom/tests/atom_integration.rs
  core/README.md
  core/src/extension.rs
  core/tests/amp.rs
  state/src/interface.rs
  urid/derive/Cargo.toml
  urid/derive/src/lib.rs
  urid/derive/src/uri_bound.rs
  urid/derive/src/urid_collection_derive.rs
  urid/derive/tests/uri_bound.rs
  urid/lv2-urid/tests/urid.rs
  urid/src/lib.rs
  urid/tests/urid.rs
Labels: enhancement

#49 Worker (closes #35)
  Cargo.toml
  README.md
  core/README.md
  src/lib.rs
  worker/Cargo.toml
  worker/LICENSE-APACHE
  worker/LICENSE-MIT
  worker/README.md
  worker/src/lib.rs
Labels: documentation, enhancement

#58 Improving the re-export crate
  Cargo.toml
  src/lib.rs
Labels: enhancement

#59 Making all macros unhygenic
  atom/src/lib.rs
  core/derive/src/lv2_descriptors.rs
  core/derive/src/port_collection_derive.rs
  core/src/extension.rs
  core/src/prelude.rs
  urid/derive/src/uri_bound.rs
  urid/derive/src/urid_collection_derive.rs
Labels: bug
