Repository RustAudio/rust-lv2, pull requests merged in 2020-07, with the labels that each got.

#72 Updating the documentation for the new sys crate
  Cargo.toml
  README.md
  atom/README.md
  atom/src/lib.rs
  core/README.md
  core/src/lib.rs
  install_examples.sh
  midi/README.md
  state/README.md
  sys/Cargo.toml
  sys/README.md
  sys/src/lib.rs
  time/README.md
  units/README.md
  urid/lv2-urid/README.md
  urid/lv2-urid/src/lib.rs
  worker/README.md
Labels: documentation

#75 Ui
  Cargo.toml
  atom/src/lib.rs
  atom/src/uris.rs
  src/lib.rs
  ui/Cargo.toml
  ui/LICENSE-APACHE
  ui/LICENSE-MIT
  ui/README.md
  ui/derive/Cargo.toml
  ui/derive/LICENSE-APACHE
  ui/derive/LICENSE-MIT
  ui/derive/README.md
  ui/derive/src/lib.rs
  ui/derive/src/lv2ui_descriptors.rs
  ui/derive/src/uiport_collection_derive.rs
  ui/src/lib.rs
  ui/src/plugin_ui.rs
  ui/src/port.rs
  ui/src/space.rs
  ui/src/uris.rs
Labels: enhancement

#78 Replace regex usage by function from std
  urid/derive/Cargo.toml
  urid/derive/src/uri_bound.rs
Labels: enhancement

#79 Fixing the installation script
  docs/README.md
  install_examples.sh
Labels: bug
